#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

# Use root/example as user/password credentials

#version: '3.1'
#services:
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/test

#mongodb:
#  test:
#    connectionString: mongodb://localhost:27017/test
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root


